#!/bin/bash

#The two lines below activate the anaconda module on Indiana University supercomputer
module unload python
module load anaconda

#User inputs
proteinCode="4x61"
conformersFile="configurations_rdkit.sdf" #Name of conformers file generated by main.py below
nConformers=10000

#Activating the conda environment and generating the conformers
conda activate test_pymol
python main.py $proteinCode $conformersFile $nConformers
conda deactivate

#Splitting the conformers xyz file and creating separate directories for energy calculations
mkdir -p molecular_files
cd molecular_files
  mv ../3XV.smi .; mv ../4x61_clean.pdb .
  mv ../configurations_rdkit.xyz .; mv ../configurations_rdkit.sdf .
  mkdir -p rdkit_conformers
  cd rdkit_conformers
    nAtomsPlusTwo=$(sed -n 4p ../configurations_rdkit.sdf | awk '{print $1 + 2}')
    ((nConformers--))
    suffix_len=$( echo -n "$nConformers" | wc -c )
    split --lines=$nAtomsPlusTwo --suffix-length=$suffix_len --numeric-suffixes --additional-suffix=.xyz ../configurations_rdkit.xyz conf_
    for i in $(seq -w 0 $nConformers); do
      echo "$i"
      mkdir -p conf_$i
      cd conf_$i
        mv ../conf_$i.xyz .
      cd ..
      mkdir -p sol_conf_$i
      cd sol_conf_$i
        cp ../conf_$i/conf_$i.xyz .
      cd ..
    done
  cd ..
cd ..

#Calling the slurm submition script to get the optimization for all the conformers
./call_slurm.tcsh

#Extracting energies from the rdkit conformer's optimization calculations
python getEnergy.py $nConformers > all_energies.txt
sort -k2rg all_energies.txt > sorted_energies.txt
python getEnergy_sol.py $nConformers > all_energies_sol.txt
sort -k2rg all_energies_sol.txt > sorted_sol_energies.txt

#Activating conda environment which has xtb installed
conda activate docking-rdock

#Running single point energy calculations for the bound 3XV configuration
cd molecular_files
  mkdir -p conf_bound
  cd conf_bound
     mv ../../3XV_H.xyz .
     xtb 3XV_H.xyz --sp -P 1 --gfn 2 > conf_bound.log
  cd ..
  mkdir -p sol_conf_bound
  cd sol_conf_bound
    cp ../conf_bound/3XV_H.xyz .
    xtb 3XV_H.xyz --sp --bhess -P 1 --gfn 2 --alpb water > conf_bound.log
  cd ..
cd ..
conda deactivate


